services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      NEO4J_URI: bolt://db:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: 12345678
  db:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/12345678
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
    volumes:
      - neo4j-data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD-SHELL", "curl", "--fail", "http://db:7474/db/data"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  neo4j-data:
